version: '3.8'
services:
  carash-server:
    build: 
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8280:8280"
    container_name: carash-server
    networks:
      - nginx_proxy
      - backend_network
    # volumes:
    #   - ./Server:/usr/src/app
    restart: always

  carash-client:
    build: 
      context: ./Client
      dockerfile: Dockerfile
    ports:
      - "8230:8230"
    container_name: carash-client
    networks:
      - nginx_proxy
      - backend_network
    restart: always

  mongodb:
    image: mongo:6.0
    container_name: ccg-mongodb
    ports:
      - "27017:27017"
    command: mongod --auth 
    volumes:
      - ./data:/data/db
    networks:
      - nginx_proxy
      - backend_network
    restart: always

networks:
  nginx_proxy:
    external: true
  backend_network:
    internal: true
